apiVersion: v1
kind: Secret
metadata:
  name: kubevirt-observability-secrets
  namespace: kubevirt-observability-system
type: Opaque
stringData:
  id_rsa.pub: "<SSH_PUBLIC_KEY_OPTIONAL>"
  loki-token: "<LOKI_BEARER_TOKEN>"
