apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: kubevirt-observability-mutating-webhook
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
webhooks:
  - name: vmmutate.kubevirt-observability.io
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    matchPolicy: Equivalent
    timeoutSeconds: 10
    clientConfig:
      service:
        namespace: kubevirt-observability-system
        name: kubevirt-observability-webhook-service
        path: /mutate-kubevirt-io-v1-virtualmachine
        port: 443
    rules:
      - operations: ["CREATE"]
        apiGroups: ["kubevirt.io"]
        apiVersions: ["v1"]
        resources: ["virtualmachines"]
