apiVersion: v1
kind: Service
metadata:
  name: kubevirt-observability-webhook-service
  namespace: kubevirt-observability-system
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: kubevirt-observability-webhook-certs
spec:
  selector:
    app: kubevirt-observability-operator
  ports:
    - name: https
      port: 443
      targetPort: 9443
